<div class="box box-primary">
    <div class="box-header">
        <i class="fa fa-bar-chart-o"></i>
        <h3 class="box-title">Bar Chart</h3>
    </div>
    <div class="box-body">
        <div id="bar-chart" style="height: 300px; padding: 0px; position: relative;">
            <canvas class="flot-base" width="467" height="330" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 425px; height: 300px;"></canvas>
            <div class="flot-text" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; font-size: smaller; color: rgb(84, 84, 84);">
                <div class="flot-x-axis flot-x1-axis xAxis x1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; display: block;"><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 70px; top: 283px; left: 20px; text-align: center;">January</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 70px; top: 283px; left: 87px; text-align: center;">February</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 70px; top: 283px; left: 163px; text-align: center;">March</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 70px; top: 283px; left: 235px; text-align: center;">April</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 70px; top: 283px; left: 306px; text-align: center;">May</div><div class="flot-tick-label tickLabel" style="position: absolute; max-width: 70px; top: 283px; left: 373px; text-align: center;">June</div></div><div class="flot-y-axis flot-y1-axis yAxis y1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; display: block;"><div class="flot-tick-label tickLabel" style="position: absolute; top: 270px; left: 7px; text-align: right;">0</div><div class="flot-tick-label tickLabel" style="position: absolute; top: 203px; left: 7px; text-align: right;">5</div><div class="flot-tick-label tickLabel" style="position: absolute; top: 135px; left: 1px; text-align: right;">10</div><div class="flot-tick-label tickLabel" style="position: absolute; top: 68px; left: 1px; text-align: right;">15</div><div class="flot-tick-label tickLabel" style="position: absolute; top: 0px; left: 1px; text-align: right;">20</div></div></div><canvas class="flot-overlay" width="467" height="330" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 425px; height: 300px;"></canvas></div>
    </div><!-- /.box-body-->
</div>